### ISSUE TITLE
Installer doesn't use device given upon installation

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite-installer-windows#42]
branch: release-0.12.0

@mikewray reported that his device was just a random hash when he logged in the central server. Apparently the installer didn't pass the information to the setup script.

**Comment by ruimalheiro** [comment]
@aronasorman could you give me a status update on this? Still happening? (Seems to be an old issue).

**Comment by aronasorman** [comment]
Not sure. @mikewray is this still the case? Closing now. Let's reopen if it's still extant.

**Comment by mikewray** [comment]
Sorry for late response guys, yes this was resolved a while back. All is well :) How is lucky 0.13.0 looking?
