### ISSUE TITLE
Build KA Lite in Microsoft Visual Studio Express 2012 generate an error

### ISSUE THREAD

**Issue by djallado** [learningequality/ka-lite-installer-windows#51]
When building KA Lite in Microsoft Visual Studio it generate an error:

**Build Error:** 
![alt text][logo]
[logo]: https://raw.githubusercontent.com/djallado/Files/master/berror.png "Build Error"

**Error List**
error `MSB8020:` The builds tools for` v110_xp (Platform Toolset = 'v110_xp')` cannot be found using the v110_xp.

**Steps to update:**
1. Click on `TOOLS` menu
2. Select `Extensions and Updates...` then another dialog will appear.
3. Click on `Update`.

**Update:** 
![alt text][logo1]
[logo1]: https://raw.githubusercontent.com/djallado/Files/master/update.png "Update"

1. Install the downloaded update in your machine
2. Click on `BUILD`.
3. Select `Build Solution`.

Then the build `KA Lite` will work fine.

**Comment by ruimalheiro** [comment]
Thanks @djallado , I'm closing this.
