### ISSUE TITLE
Unclean uninstallation process 

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite-installer-windows#57]
Uninstalling current develop results in multiple folders left in installation folder.
![screenshot from 2015-02-13 11 53 38](https://cloud.githubusercontent.com/assets/4349806/6193563/b69e903e-b379-11e4-947c-2ae45c6666ff.png)

**Comment by aronasorman** [comment]
@ruimalheiro can you try debugging this?

**Comment by ruimalheiro** [comment]
Thanks @EdDixon and @aronasorman 

I'll check this asap. :+1:

**Comment by EdDixon** [comment]
This is expected behavior to allow for an inplace upgrade to the next version.

**Comment by ruimalheiro** [comment]
This was fixed on PR19 under installers repo.
