### ISSUE TITLE
Ignore data.sqlite

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite-installer-windows#59]
To avoid mistakes, let's just avoid placing data.sqlite when bundling files into our installer. 

I'd mark this is critical if we had a label for it.

**Comment by cpauya** [comment]
Now setting-up my virtual machine for this.

**Comment by cpauya** [comment]
Uhm @aronasorman - what do you mean by "not including the database"?   The `ka-lite` is a sub-module - where the database is ignored.  By bundling, do you mean when we include the contents / json?

**Comment by aronasorman** [comment]
Hi @cpauya, by "not including the database" meaning making sure it's not part of the bundled files for the installer. I see in `KALiteSetup.iss` that we just include all files inside the `ka-lite` directory. Maybe there's a way to exclude directories inside included directories, similar to `gitignore`?

**Comment by cpauya** [comment]
I see, yes there's an `Excludes` keyword as per documented here: http://www.jrsoftware.org/ishelp/index.php?topic=filessection.  This is the related entry at `KALiteSetup.iss`:

> [Files]
> ...
> Source: "..\ka-lite\kalite\database\*"; DestDir: "{app}\ka-lite\kalite\database"; Flags: ignoreversion recursesubdirs createallsubdirs uninsneveruninstall
> ...

So adding an `Excludes` would yield this change:


> [Files]
> ...
> Source: "..\ka-lite\kalite\database\*"; DestDir: "{app}\ka-lite\kalite\database"; Excludes: "data.sqlite"; Flags: ignoreversion recursesubdirs createallsubdirs uninsneveruninstall
> ...

Will test this further and issue a PR after.
