### ISSUE TITLE
Stop server option in 0.13 systray ico does not stop server

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite-installer-windows#64]
Selecting stop server from the systray icon options in 0.13 does not stop the server. This is made worse by the fact that the popup closes once the option has been selected hiding the fact that the server is still running.  On subsequent checks from the same icon you will see that the server is not in the stopped state.

**Comment by aronasorman** [comment]
This repo is deprecated. Open issues in https://github.com/learningequality/installers

**Comment by MCGallaspy** [comment]
@aronasorman since when is this repo deprecated? I've been using as lately as a couple weeks ago. Perhaps we should delete it?

**Comment by aronasorman** [comment]
Was deprecated ever since this PR was merged, transferring the files from here to the installers repo: https://github.com/learningequality/installers/pull/14
